services:
  opentripplanner:
    image: docker.io/opentripplanner/opentripplanner:latest
    container_name: otp-montreal
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./otp-data:/var/opentripplanner
    environment:
      - JAVA_OPTIONS=-Xmx4G
      - STM_API_KEY=${STM_API_KEY}
    command: ["--build", "--save", "--serve"]